name: test-main

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        std: ["", "alloc,", "std,"]
        spin: ["", "spin,"]
        parking_lot: ["", "parking_lot,"]
        triple: ["", "triple,", "broad"]
        flip: ["", "ring-buffer,", "flip-queue",]
    steps:
    - uses: actions/checkout@v4
    - name: Run cargo test
      run: cargo +nightly test --all --features=${{ matrix.std }}${{ matrix.spin }}${{ matrix.parking_lot }}${{ matrix.triple }}${{ matrix.flip }}
